## Bag of words

pip install scikit-learn

In [1]:
import numpy as np
import pandas as pd

In [36]:
df = pd.DataFrame({"text":["people watch youtube",
                         "youtube watch youtube",
                         "people write comment",
                          "youtube write comment"],"output":[1,1,0,0]})

df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [38]:
bow = cv.fit_transform(df['text'])

In [39]:
#vocabulary : all unique words
print(cv.vocabulary_)

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}


In [40]:
bow.toarray()

array([[0, 1, 1, 0, 1],
       [0, 0, 1, 0, 2],
       [1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1]])

In [41]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 0 1]]
[[0 0 1 0 2]]
[[1 1 0 1 0]]


In [44]:
# new
cv.transform(['Bappy watch youtube']).toarray()

array([[0, 0, 1, 0, 1]])

In [45]:
X = bow.toarray()
y = df['output']

In [46]:
X

array([[0, 1, 1, 0, 1],
       [0, 0, 1, 0, 2],
       [1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1]])

In [47]:
y

0    1
1    1
2    0
3    0
Name: output, dtype: int64

##  N-grams

In [28]:
df = pd.DataFrame({"text":["people watch youtube",
                         "youtube watch youtube",
                         "people write comment",
                          "youtube write comment"],"output":[1,1,0,0]})

df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [29]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [30]:
bow = cv.fit_transform(df['text'])

In [31]:
print(cv.vocabulary_)

{'people watch': 0, 'watch youtube': 2, 'youtube watch': 4, 'people write': 1, 'write comment': 3, 'youtube write': 5}


In [32]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 1 0 0 0]]
[[0 0 1 0 1 0]]
[[0 1 0 1 0 0]]


In [48]:
#Ti gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [34]:
bow = cv.fit_transform(df['text'])

In [35]:
print(cv.vocabulary_)

{'people watch youtube': 0, 'youtube watch youtube': 2, 'people write comment': 1, 'youtube write comment': 3}


In [21]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]


## TF-IDF (Term frequency- Inverse document frequency)

In [27]:
df = pd.DataFrame({"text":["people watch youtube",
                         "youtube watch youtube",
                         "people write comment",
                          "youtube write comment"],"output":[1,1,0,0]})

df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [24]:
arr = tfid.fit_transform(df['text']).toarray()

In [25]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [26]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
